package interpreter;

public enum Operation {
	LOAD, LOADC, STORE,
	ADD, SUB, MUL, DIV, INC, DEC,
	EQUAL, INF, SUP, INFE, SUPE, NEQUAL,
	JZERO, JUMP, JNZERO,
	JUMPG, JUMPNG, JUMPGE, JUMPNGE,
	JUMPL, JUMPNL, JUMPLE, JUMPNLE,
	AND, OR, XOR, NOT,
	WRITEC, WRITE, READC, READ,
	END, ERROR;
}
